version: "3.5"

services:
  # mongo database
  database:
    image: mongo:latest
    container_name: react_database
    volumes:
      - ./mongo-dev/db:/data/db
    # ports:
    #   - 27018:27017  

  # backend
  backend:
    build: backend/
    image: backend-react
    container_name: backend-react
    restart: always
    environment:
      - MONGO_HOST=database
      - MONGO_PORT=27017
    volumes:
      - cmreact-volume:/usr/src/app/build/uploaded
    ports:
      - 8081:8081
    depends_on:
      - database
    
  # frontend 
  frontend:
    image: frontend
    build:
      context: frontend/
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 81:80


volumes:
  cmreact-volume:
    name: cmreact-volume
    external: false
  